ALTER TABLE user_stats ADD COLUMN current_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user_stats ADD COLUMN max_streak INTEGER NOT NULL DEFAULT 0;

ALTER TABLE chat_settings ADD COLUMN win_amount INTEGER NOT NULL DEFAULT 64;
